checkpoint_freq: 1000
opt_level: O0
display_kp_rows: 4
display_freq: 5000

transporter_combine_mode: max

processes: 7
cma_algo: fast
cma_step_mode: auto
cma_step_decay: 0.001
cma_oversample: 0

policy_action_select_mode: argmax
policy_depth: 1