checkpoint_freq: 10000
display_freq: 10000
model_type: VGG_PONG_LAYERNECK
model_in_channels: 1
model_z_channels : 16

dataset: pong
dataset_train_len: 19000
dataset_test_len: 1100
dataset_randomize: True

batch_size: 120
epochs: 1000
opt_level: O2