checkpoint_freq: 1
cma_algo: fast

model_type: VGG_PONG_LAYERNECK
model_in_channels: 3
model_z_channels : 16
model_keypoints : 3
load: /home/duane/keypoints/data/models/transporter/VGG_PONG_LAYERNECK/run_40/best/
dataset: pong_color
dataset_train_len: 20000
dataset_test_len: 2100
dataset_randomize: True
data_aug_type: None

batch_size: 32
epochs: 60
opt_level: O2
